### ISSUE TITLE
Why isn't the newest version of conda-build used?

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/conda-forge-build-setup-feedstock#38]
This is causing issues for the [emacs feedstock](https://github.com/conda-forge/emacs-feedstock/pull/3), because I need a fix that is only in the latest version of conda-build (or at least newer than what this uses).

**Comment by asmeurer** [comment]
I guess it was because of https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/27. Has this been fixed upstream yet? Or worked around downstream?

**Comment by jakirkham** [comment]
Sort of... :thinking: Basically it is fixed in the script here. However, to use the script here feedstocks need to be [re-rendered](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy` version `1.3.x` (in practice `x` should be `2` to get other important fixes).

Edit: By fixes to the upload script I mean PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/34 ).

**Comment by jakirkham** [comment]
The real problem that is a blocker is that `cmake` doesn't seem to work on `conda-build` version `2.0.x`. Please see issue ( https://github.com/conda-forge/cmake-feedstock/issues/21 ). If we can solve that, we should be in pretty good shape to proceed. If you have time to look into it, we would certainly appreciate the help.

**Comment by asmeurer** [comment]
Re that issue: I'm out of the loop these days, but I thought that long prefix length was increased. 

Regardless, wouldn't it be better to use the newest version by default, and only pin an older version for packages that are broken? This is preventing any fixes/improvements in conda-build from making their way to any conda-forge builds. So long as the conda-build developer(s) are paying attention to conda-forge issues, it should be preferable to use the newest version by default. Or are manual workarounds to the .yml files looked down upon?

**Comment by ocefpaf** [comment]
I agree entirely with @asmeurer. BTW that was the original setup we had before this package was introduced. Notice that pinning only when necessary was also easier before because the conda/conda-build versions where in conda-smithy and people could easily see them in the CIs configuration explicitly, instead of digging into layers of dubious advantages. Also, before this package we did not had to http://xkcd.com/1739/ like in https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/29 :smile:

**Comment by asmeurer** [comment]
Another (advantage?) to manually pinning in `*.yml` is that it will need to be manually kept in with each rerender, meaning the rerenders provide an impetus to check if the pinning is still necessary.

**Comment by ocefpaf** [comment]
> Another (advantage?) to manually pinning in `*.yml` is that it will need to be manually kept in with each rerender, meaning the rerenders provide an impetus to check if the pinning is still necessary. 

That "advantage?" was part of Phil's original design BTW.

**Comment by ocefpaf** [comment]
@pelson it seems that @jjhelmus already implemented the extra `config` argument in https://github.com/conda-forge/conda-forge-build-setup-feedstock/commit/e35cc086a5b64d9f7512f099206bcd133072a675

But I see that there are other [calls](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py#L59) to `bldpkg_path` in the script. Those are addressed in 
https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/39 by @shadowwalkersb BTW.

So the only issue here is the rendering of the `conda-forge-build-setup-feedstock` itself.

**Comment by jakirkham** [comment]
We are now on `conda-build` 2. Details of what went into the switch and related discussion are in issue ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/40 ).
