### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by rmax** [conda-forge/conda-forge-build-setup-feedstock#57]
I got this error in a Travis build which I cannot find after restarted :(

```
Building all recipes.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5215  100  5215    0     0  37591      0 --:--:-- --:--:-- --:--:-- 37789
Checking to see if this PR build is outdated.
Traceback (most recent call last):
  File "<stdin>", line 192, in <module>
  File "<stdin>", line 181, in main
  File "<stdin>", line 93, in travis_check_latest_pr_build
ValueError: max() arg is an empty sequence
```

xref: https://github.com/conda-forge/staged-recipes/pull/2463

**Comment by jakirkham** [comment]
Thanks @rolando. Sorry to confound the debugging by restarting the CI.

FWIW I think I know what that script is complaining about, but am confused as to why it is happening. That said, I already have a workaround in mind.

**Comment by jakirkham** [comment]
This apparently occurred with the restarted build too. I remain unclear on why Travis CI had this issue with this particular PR, but can verify from the API directly that it is not included is the list of builds completed or otherwise. Have a patch incoming to workaround this issue. Though we should definitely relay this information to Travis CI so that they can look into it further.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/59 ) for the proposed workaround.
