### ISSUE TITLE
Pin conda-build to 2.1.4

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-build-setup-feedstock#58]
conda-build 2.1.5 has issues with symbolic links to folders.

See https://github.com/conda/conda-build/issues/1769

See these 2 builds,
https://travis-ci.org/isuruf/gap-feedstock/builds/205237069
https://travis-ci.org/isuruf/gap-feedstock/builds/205250278

Only difference is that the last build is using conda-build 2.1.4

**Comment by jakirkham** [comment]
Thanks @isuruf.

We actually only have released `conda-build` 2.1.4. The issue is we didn't have a Python 3.6 build of it. So `conda` resorted to getting the latest version from `defaults` as channel priority was not an issue.

Had put in a PR ( https://github.com/conda-forge/conda-build-feedstock/pull/17 ) to get `conda-build` built for Python 3.6. CI only just finished today. So have merged it. Looks like we now have releases on all platforms. In other words, this issue should be solved.

**Comment by isuruf** [comment]
Thanks, that works. We might want to go from 2.1.4 straight to the release after 2.1.5 and skip 2.1.5
